import Head from "next/head";
import Center from "@/components/Layout/Center";
import Header from "@/components/Layout/Header";
import Landing from "@/components/Landing";
import Footer from "@/components/Layout/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>MOGA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <Center>
        <Landing />
        <Footer />
      </Center>
    </>
  );
}
