import { useState, useEffect } from "react";
import Head from "next/head";
import Center from "@/components/Layout/Center";
import Header from "@/components/Layout/Header";
import Landing from "@/components/Landing";
import Footer from "@/components/Layout/Footer";
import Popup from "@/components/Popup";

export default function Home() {
  const [showPopup, setShowPopup] = useState(false);

  useEffect(() => {
    // localStorage에서 마지막 닫은 시간 확인
    const popupDismissed = localStorage.getItem("popupDismissed");
    if (
      !popupDismissed ||
      Date.now() - Number(popupDismissed) > 24 * 60 * 60 * 1000
    ) {
      setShowPopup(true);
    }
  }, []);

  const handlePopupClose = (isOpen, oneDay = false) => {
    setShowPopup(isOpen);
    if (!isOpen && oneDay) {
      localStorage.setItem("popupDismissed", Date.now().toString());
    }
  };

  return (
    <>
      <Head>
        <title>MOBICK SHELL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <Center>
        <Landing />
        <Footer />
      </Center>

      <Popup showPopup={showPopup} setShowPopup={handlePopupClose} />
    </>
  );
}
