import Head from "next/head";
import Header from "@/components/Layout/Header";
import Verification from "@/components/MainVerification";
import Center from "@/components/Layout/Center";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Tailwind CSS 유틸리티 클래스를 각 컴포넌트에서 사용하세요. */}
      <Center>
        <Header />
        <Verification />
      </Center>
    </>
  );
}
